name: Notifier
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify Pull Request
      uses: rtCamp/action-slack-notify@v2.1.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: devchat
        SLACK_COLOR: '#e52335'
        SLACK_ICON: https://threads-logos.s3-eu-west-1.amazonaws.com/Threads.jpg
        SLACK_TITLE: ":bulb: Developer Handbook suggestion by ${{github.actor}}"
        SLACK_MESSAGE: "${{github.event.pull_request.title}} - ${{github.event.pull_request.html_url}}"
        SLACK_USERNAME: DevHandbook
        MSG_MINIMAL: true
    - name: Slack Notify Merge
      uses: rtCamp/action-slack-notify@v2.1.0
      if: github.event_name == 'push'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: devchat
        SLACK_COLOR: '#e52335'
        SLACK_ICON: https://threads-logos.s3-eu-west-1.amazonaws.com/Threads.jpg
        SLACK_TITLE: ":white_check_mark: Developer Handbook suggestion by ${{github.actor}} merged"
        SLACK_MESSAGE: "${{github.event.repository.html_url}}"
        SLACK_USERNAME: DevHandbook
        MSG_MINIMAL: true        
